const authView=document.getElementById('authView'),dashboard=document.getElementById('dashboardView');
const authForm=document.getElementById('authForm'),authMessage=document.getElementById('authMessage');
let allRequests=[],selectedRequest=null;
async function api(url,options={}){const response=await fetch(url,{...options,headers:{...(options.body?{'Content-Type':'application/json'}:{}),...(options.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Something went wrong.');return data;}
function esc(value){return String(value||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function niceDate(value){return new Date(value).toLocaleString('en-PH',{dateStyle:'medium',timeStyle:'short'});}
async function checkSession(){try{const {staff}=await api('/api/auth/me');showDashboard(staff);}catch{authView.hidden=false;dashboard.hidden=true;}}
function showDashboard(staff){authView.hidden=true;dashboard.hidden=false;document.getElementById('welcomeName').textContent=staff.name.split(' ')[0];document.getElementById('staffBadge').textContent=staff.rank;loadDashboard();}
authForm.addEventListener('submit',async event=>{event.preventDefault();authMessage.textContent='Signing in…';try{const {staff}=await api('/api/auth/login',{method:'POST',body:JSON.stringify({name:document.getElementById('staffName').value.trim(),password:document.getElementById('staffPassword').value})});showDashboard(staff);}catch(error){authMessage.textContent=error.message;}});
document.getElementById('logoutButton').addEventListener('click',async()=>{await api('/api/auth/logout',{method:'POST'}).catch(()=>{});location.reload();});
function renderRequests(){const pending=allRequests.filter(r=>r.status==='pending');document.getElementById('pendingCount').textContent=pending.length;document.getElementById('pendingNavCount').textContent=pending.length;document.getElementById('approvedCount').textContent=allRequests.filter(r=>['accepted','checked_in'].includes(r.status)).length;document.getElementById('checkedInCount').textContent=allRequests.filter(r=>r.status==='checked_in').length;const list=document.getElementById('requestList'),empty=document.getElementById('requestEmpty');empty.hidden=pending.length>0;list.innerHTML=pending.map(r=>`<article class="request-card"><div class="visitor-details"><header><strong>${esc(r.name)}</strong><span class="status-tag pending">Waiting</span></header><p>${esc(r.email)} · ${esc(r.phone)} · ${esc(niceDate(r.createdAt))}</p><p class="reason">${esc(r.reason)}</p><small>Reference ${esc(r.reference)}</small></div><div class="request-actions"><button class="decision-button view-slip" data-view-slip="${esc(r.id)}">View entry slip</button><button class="decision-button accept" data-decision="accepted" data-id="${esc(r.id)}">Accept</button><button class="decision-button decline" data-decision="declined" data-id="${esc(r.id)}">Decline</button></div></article>`).join('');renderHistory();}
function renderHistory(){const filter=document.getElementById('historyFilter').value;const rows=allRequests.filter(r=>r.status!=='pending'&&(filter==='all'||r.status===filter));document.getElementById('historyEmpty').hidden=rows.length>0;document.getElementById('historyList').innerHTML=rows.map(r=>`<article class="history-row"><div><strong>${esc(r.name)} · ${esc(r.reference)}</strong><p>${esc(r.reason)} · ${esc(r.email)} · ${esc(niceDate(r.decidedAt||r.checkedInAt||r.createdAt))}</p></div><span class="status-tag ${esc(r.status)}">${r.status==='checked_in'?'Checked in':esc(r.status)}</span></article>`).join('');}
async function loadDashboard(){try{const {requests}=await api('/api/requests');allRequests=requests;renderRequests();}catch(error){if(error.message.includes('sign in')||error.message.includes('Session'))location.reload();else document.getElementById('requestList').innerHTML=`<p class="form-message">${esc(error.message)}</p>`;}}
async function decide(id,status){try{await api(`/api/requests/${encodeURIComponent(id)}/decision`,{method:'POST',body:JSON.stringify({status})});document.getElementById('slipModal').hidden=true;await loadDashboard();}catch(error){alert(error.message);}}
function viewSlip(id){selectedRequest=allRequests.find(request=>request.id===id);if(!selectedRequest)return;const r=selectedRequest;document.getElementById('slipDetails').innerHTML=`<div><span>Visitor</span><strong>${esc(r.name)}</strong></div><div><span>Contact number</span><strong>${esc(r.phone)}</strong></div><div><span>Email</span><strong>${esc(r.email)}</strong></div><div><span>Reason for entering</span><strong>${esc(r.reason)}</strong></div><div><span>Submitted</span><strong>${esc(niceDate(r.createdAt))}</strong></div><div><span>Reference</span><strong>${esc(r.reference)}</strong></div>`;document.getElementById('slipModal').hidden=false;}
document.getElementById('refreshButton').addEventListener('click',loadDashboard);
document.getElementById('historyFilter').addEventListener('change',renderHistory);
document.getElementById('requestList').addEventListener('click',event=>{const view=event.target.closest('[data-view-slip]');if(view){viewSlip(view.dataset.viewSlip);return;}const button=event.target.closest('[data-decision]');if(button){button.disabled=true;decide(button.dataset.id,button.dataset.decision);}});
document.getElementById('closeSlip').addEventListener('click',()=>document.getElementById('slipModal').hidden=true);
document.getElementById('slipModal').addEventListener('click',event=>{if(event.target.id==='slipModal')event.currentTarget.hidden=true;});
document.getElementById('slipAccept').addEventListener('click',()=>selectedRequest&&decide(selectedRequest.id,'accepted'));
document.getElementById('slipDecline').addEventListener('click',()=>selectedRequest&&decide(selectedRequest.id,'declined'));
checkSession();setInterval(()=>{if(!dashboard.hidden)loadDashboard();},30000);

